export const api = {
  attachments: {
    pickLocal: () => window.courrier.attachments.pickLocal(),
    registerDroppedFiles: window.courrier.attachments.registerDroppedFiles,
    open: window.courrier.attachments.open,
    download: window.courrier.attachments.download,
  },
  auth: {
    getSession: () => window.courrier.auth.getSession(),
    signIn: window.courrier.auth.signIn,
    switchAccount: window.courrier.auth.switchAccount,
    signOut: window.courrier.auth.signOut,
  },
  mail: {
    getCapabilities: window.courrier.mail.getCapabilities,
    listFolders: window.courrier.mail.listFolders,
    listMessages: window.courrier.mail.listMessages,
    getMessage: window.courrier.mail.getMessage,
    searchMessages: window.courrier.mail.searchMessages,
    markMessageReadState: window.courrier.mail.markMessageReadState,
    moveMessage: window.courrier.mail.moveMessage,
    deleteMessage: window.courrier.mail.deleteMessage,
    archiveMessage: window.courrier.mail.archiveMessage,
    markMessageJunkState: window.courrier.mail.markMessageJunkState,
    setMessageStarState: window.courrier.mail.setMessageStarState,
    setMessageFlagState: window.courrier.mail.setMessageFlagState,
    setMessageImportantState: window.courrier.mail.setMessageImportantState,
    listPeople: window.courrier.mail.listPeople,
    sendMessage: window.courrier.mail.sendMessage,
    replyToMessage: window.courrier.mail.replyToMessage,
    onRemoteChange: window.courrier.mail.onRemoteChange,
    onOpenMessage: window.courrier.mail.onOpenMessage,
  },
  notifications: {
    getSettings: window.courrier.notifications.getSettings,
    updateSettings: window.courrier.notifications.updateSettings,
  },
  window: {
    closeCurrent: () => window.courrier.window.closeCurrent(),
    getComposeDraft: () => window.courrier.window.getComposeDraft(),
    openComposeWindow: window.courrier.window.openComposeWindow,
  },
};
